# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tctrl-annotations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tctrl-annotations.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17tctrl-annotations.proto\x1a google/protobuf/descriptor.proto:1\n\x08json_key\x12\x1d.google.protobuf.FieldOptions\x18\xb8\x8e\x03 \x01(\t')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


JSON_KEY_FIELD_NUMBER = 51000
json_key = _descriptor.FieldDescriptor(
  name='json_key', full_name='json_key', index=0,
  number=51000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['json_key'] = json_key

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(json_key)

# @@protoc_insertion_point(module_scope)
